FORMAT: 1A
HOST: https://feednyc.onrender.com/api/places/

# Pocket Pantry API

This document outlines the usage of the Pocket Pantry API. Pocket Pantry is a project by Local Devs that aims to centralize information about food assistance programs in New York City.

Base URL: https://feednyc.onrender.com/api/places

👉 Check out & Star the project on [Github](https://github.com/Official-LocalDevs/FeedNYC-API/tree/main)!

👉 Learn more about [LocalDevs](localdevs.city) and follow us on [LinkedIn](https://www.linkedin.com/company/localdevs)!

## Endpoints


| Route                     | Description                                                                       | Link                                                          |
| -------------             | -------------                                                                     | -------------                                                 |
| `/getAll`                 | Retrieves all food pantries and soup kitchens                                     | [Go to Section](#reference/0/get-all-places)                  |
| `/id/{id}`                | Retrieves a place based on a unique ID                                            | [Go to Section](#reference/0/get-place-by-id)                 |
| `/borough/{borough}`      | Retrieves places based on the borough                                             | [Go to Section](#reference/0/get-places-by-borough)           |
| `/tags/{tags}`            | Retrieves places associated with specific tags                                    | [Go to Section](#reference/0/get-places-by-tags)              |
| `/type/{type}`            | List of Related pictures                                                          | [Go to Section](#reference/0/get-places-by-type)              |
| `/time/{open}/{close}`    | Retrieves places based on their open and closing times                            | [Go to Section](#reference/0/get-places-by-operating-times)   |
| `/days/{days}`            | Retrieved list of places based on whether or not they are open on a specific day  | [Go to Section](#reference/0/get-places-by-day)               |
| `/search`                 | Search route using query parameters                                               | [Go to Section](#reference/0/search)                          |


### Get All Places [/getAll]
**Retrieves all places from the database**

#### Example

| Example   | Description                                      |
| --------- | ------------------------------------------------ |
| `/getAll` | Retrieves all places from the database           |


#### Fetch Resource [GET]

+ Response 200 (application/json)
    + Attributes (array[Place])
    + Body
    ```json
    [
      {
        "_id": "660a91248747cd35103e54ba",
        "name": "Al Hajjah Fajr Tyson Halal Food and Clothing Distribution Pantry",
        "address": "2269 Crotona Ave, Bronx, NY, 10457",
        "contact": "(646) 353-0859",
        "tags": ["Halal"],
        "hours": {
          "food_pantry": {
            "Monday": [{"_id": "664d493a8d28da79ee488277", "open": "13:00", "close": "17:00"}],
            "Tuesday": [{"_id": "664d493a8d28da79ee488278", "open": "13:00", "close": "17:00"}],
            "Wednesday": [{"_id": "664d493a8d28da79ee488279", "open": "13:00", "close": "17:00"}],
            "Thursday": [{"_id": "664d493a8d28da79ee48827a", "open": "13:00", "close": "17:00"}],
            "Friday": [{"_id": "664d493a8d28da79ee48827b", "open": "13:00", "close": "17:00"}],
            "Saturday": [{"_id": "664d493a8d28da79ee48827c", "open": "13:00", "close": "17:00"}],
            "Sunday": [{"_id": "664d493a8d28da79ee48827d", "open": "13:00", "close": "17:00"}]
          },
          "_id": "664d493a8d28da79ee48827e"
        },
        "borough": "Bronx",
        "notes": []
      }
    ]
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "Places not found" }
    ```

### Get Place by ID [/id/{id}]


**Retrieves a place based on a unique ID**

#### Parameters

| Parameter | Type   | Description                              |
| --------- | ------ | -------------------------------------    |
| `id`      | string | Must be a valid ID for an existing place |

#### Examples

| Example               | Validity       | Description                                      |
| --------------------- | -------------- | ------------------------------------------------ |
| `/id/660a91248747cd35103e54be` | Valid          | Retrieves a place with the specified ID           |
| `/id/1`               | Invalid        | No place exists with an ID of 1                  |


#### Fetch Resource [GET]

+ Parameters
    + id: `660a91248747cd35103e54be` (string, required) - The ID of the place to retrieve.
+ URL Params: 
    + Required: `id=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Body
    ```json
    {
      "tags": [],
      "_id": "660a91248747cd35103e54be",
      "name": "Calvary Delivery Christian Assembly",
      "address": "737-739 Concourse Village West Bronx, NY, 10451",
      "contact": "(347) 658-4459",
      "notes": [
        {
          "_id": "664d47d88d28da79ee488198",
          "for": "All",
          "note": "Once a month, please call for date"
        }
      ],
      "borough": "Bronx"
    }
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "Place not found" }
    ```

### Get Places by Borough [/borough/{borough}]

**Retrieves places based on the borough**

#### Parameters
| Parameter  | Type   | Enum Values                                         | Description                 |
| ---------- | ------ | ---------------------------------------------------- | --------------------------- |
| `borough`  | string | `Queens`, `Brooklyn`, `Bronx`, `Manhattan`, `Staten Island` | Specifies the borough of the place |

#### Examples

| Example                   | Validity       | Description                                      |
| ------------------------- | -------------- | ------------------------------------------------ |
| `/borough/Queens`         | Valid          | Retrieves places in the borough of Queens        |
| `/borough/Brooklyn`       | Valid          | Retrieves places in the borough of Brooklyn      |
| `/borough/Brook`          | Invalid        | 'Brook' is not a valid borough in NYC            |


#### Fetch Resource [GET]
+ Parameters
    + borough: `Bronx` (string, required) - The borough to filter places by.
+ URL Params: 
    + Required: `borough=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Attributes (array[Place])
    + Body
    ```json
    {
      "_id": "660a91248747cd35103e54ba",
      "name": "Al Hajjah Fajr Tyson Halal Food and Clothing Distribution Pantry",
      "address": "2269 Crotona Ave, Bronx, NY, 10457",
      "contact": "(646) 353-0859",
      "tags": ["Halal"],
      "hours": {
        "food_pantry": {
          "Monday": [{"_id": "664d3fd55163ad574f6d9bd4", "open": "13:00", "close": "17:00"}],
          "Tuesday": [{"_id": "664d3fd55163ad574f6d9bd5", "open": "13:00", "close": "17:00"}],
          "Wednesday": [{"_id": "664d3fd55163ad574f6d9bd6", "open": "13:00", "close": "17:00"}],
          "Thursday": [{"_id": "664d3fd55163ad574f6d9bd7", "open": "13:00", "close": "17:00"}],
          "Friday": [{"_id": "664d3fd55163ad574f6d9bd8", "open": "13:00", "close": "17:00"}],
          "Saturday": [{"_id": "664d3fd55163ad574f6d9bd9", "open": "13:00", "close": "17:00"}],
          "Sunday": [{"_id": "664d3fd55163ad574f6d9bda", "open": "13:00", "close": "17:00"}]
        },
        "_id": "664d3fd55163ad574f6d9bdb"
      },
      "borough": "Bronx",
      "notes": []
    }
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "No places found in this borough" }
    ```

### Get Places by Tags [/tags/{tags}]

**Retrieves places associated with specific tags**

#### Parameters
| Parameter | Type   | Enum Values                               | Description                                      |
| --------- | ------ | ----------------------------------------- | ------------------------------------------------ |
| `tags`    | string | `Halal`, `Kosher`, `Vegetarian`, `HIV Customers` | Comma-separated string including all query tags  |

#### Examples

| Example                           | Validity       | Description                                      |
| --------------------------------- | -------------- | ------------------------------------------------ |
| `/tags/Halal,Kosher,Vegetarian`   | Valid          | Retrieves places with tags 'Halal', 'Kosher', and 'Vegetarian' |
| `/tags/Halal`                     | Valid          | Retrieves places with the tag 'Halal'            |
| `/tags/Halal+Kosher+Vegetarian`   | Invalid        | Cannot use `+` to separate tag values            |
| `/tags/Halal,Vegan`               | Invalid        | 'Vegan' is not a valid tag option                |


#### Fetch Resource [GET]
+ Parameters
    + tags: `Halal` (string, required) - The tags to filter places by.
+ URL Params: 
    + Required: `tags=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Attributes (array[Place])
    + Body
    ```json
    [
      {
        "_id": "660a91248747cd35103e54ba",
        "name": "Al Hajjah Fajr Tyson Halal Food and Clothing Distribution Pantry",
        "address": "2269 Crotona Ave, Bronx, NY, 10457",
        "contact": "(646) 353-0859",
        "tags": ["Halal"],
        "hours": {
          "food_pantry": {
            "Monday": [{"_id": "664d47768d28da79ee488085", "open": "13:00", "close": "17:00"}],
            "Tuesday": [{"_id": "664d47768d28da79ee488086", "open": "13:00", "close": "17:00"}],
            "Wednesday": [{"_id": "664d47768d28da79ee488087", "open": "13:00", "close": "17:00"}],
            "Thursday": [{"_id": "664d47768d28da79ee488088", "open": "13:00", "close": "17:00"}],
            "Friday": [{"_id": "664d47768d28da79ee488089", "open": "13:00", "close": "17:00"}],
            "Saturday": [{"_id": "664d47768d28da79ee48808a", "open": "13:00", "close": "17:00"}],
            "Sunday": [{"_id": "664d47768d28da79ee48808b", "open": "13:00", "close": "17:00"}]
          },
          "_id": "664d47768d28da79ee48808c"
        },
        "borough": "Bronx",
        "notes": []
      }
    ]
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "No places found with these tags" }
    ```

### Get Places by Type [/type/{type}]

**Retrieves places by their type**

#### Parameters
| Parameter | Type   | Enum Values                | Description                    |
| --------- | ------ | -------------------------- | ------------------------------ |
| `type`    | string | `food_pantry`, `soup_kitchen` | Specifies the type of place    |

#### Examples

| Example                     | Validity       | Description                                      |
| --------------------------- | -------------- | ------------------------------------------------ |
| `/type/food_pantry`         | Valid          | Retrieves places of type 'food_pantry'           |
| `/type/soup_kitchen`        | Valid          | Retrieves places of type 'soup_kitchen'          |
| `/type/foodPantry`          | Invalid        | 'foodPantry' is not an accepted value            |
| `/type/food_cart`           | Invalid        | 'food_cart' is not an accepted value             |


#### Fetch Resource [GET]

+ Parameters
    + type: `food_pantry` (string, required) - The type of places to retrieve.
+ URL Params: 
    + Required: `type=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Body
    ```json
    [
        {
            "_id": "660880ef8747cd9210f22d03",
            "name": "CHURCH OF ST. NICHOLAS OF TOLENTINE",
            "address": "2345 University Ave, Bronx, NY, 10468",
            "contact": "(718) 295-6800",
            "tags": [],
            "hours": {
                "food_pantry": {
                    "Tuesday": [
                        {
                            "_id": "668051da4899dda2c55ddc3c",
                            "open": "09:00",
                            "close": "11:00"
                        }
                    ]
                },
                "_id": "668051da4899dda2c55ddc3d"
            },
            "borough": "Bronx",
            "notes": []
        },
        {
            "_id": "660880f28747cd9210f22d04",
            "name": "BREAD OF LIFE FOOD PANTRY",
            "address": "1104 Elder Ave, Bronx, NY, 10472",
            "contact": "(347) 235-3723",
            "tags": [],
            "hours": {
                "food_pantry": {
                    "Saturday": [
                        {
                            "_id": "668051da4899dda2c55ddc3e",
                            "open": "13:30",
                            "close": "16:30"
                        }
                    ]
                },
                "_id": "668051da4899dda2c55ddc3f"
            },
            "borough": "Bronx",
            "notes": []
        }
    ]
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "No places found of this type" }
    ```

### Get Places by Operating Times [/time/{open}/{close}]

**Retrieves places based on their open and closing times**

#### Parameters
| Parameter | Type   | Format | Description                                      |
| --------- | ------ | ------ | ------------------------------------------------ |
| `open`    | string | hh:mm  | Open time in 24-hour format, Eastern Time (NYC)  |
| `close`   | string | hh:mm  | Close time in 24-hour format, Eastern Time (NYC) |

##### Comments
* All parameters must be in 24-hour time, in hh:mm format, and in Eastern Time (NYC).
* `close` time must be later than `open` time.

#### Examples

| Example                 | Validity       | Description                                      |
| ----------------------- | -------------- | ------------------------------------------------ |
| `/time/13:00/17:00`     | Valid          | Retrieves places open from 13:00 to 17:00        |
| `/time/03:00/07:00`     | Valid          | Retrieves places open from 03:00 to 07:00        |
| `/time/12:00/01:00`     | Invalid        | Close time '01:00' is earlier than open time '12:00' |
| `/time/12:00/1:00`      | Invalid        | Incorrect format for '1:00', should be '01:00'    |


#### Fetch Resource [GET]

+ Parameters
    + open: `13:00` (string, required) - Opening time to filter places by.
    + close: `17:00` (string, required) - Closing time to filter places by.
+ URL Params: 
    + Required: `open=[string], close=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Body
    ```json
    [See relevant place data]
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "No places found within these operating times" }
    ```

### Get Places by Day [/days/{days}]

**Retrieves places based on what days they are open on**

#### Parameters
| Parameter | Type   | Enum Values                                          | Description                                      |
| --------- | ------ | ---------------------------------------------------- | ------------------------------------------------ |
| `days`    | string | `Monday`, `Tuesday`, `Wednesday`, `Thursday`, `Friday`, `Saturday`, `Sunday` | Days of the week places are open                 |

#### Examples

| Example                           | Validity       | Description                                      |
| --------------------------------- | -------------- | ------------------------------------------------ |
| `/days/Monday,Tuesday,Friday`     | Valid          | Retrieves places open on Monday, Tuesday, and Friday |
| `/days/Monday`                   | Valid          | Retrieves places open on Monday                  |
| `/days/Monday,Twosday`           | Invalid        | 'Twosday' is not a valid day                     |


#### Fetch Resource [GET]
+ Parameters
    + days: `Monday,Tuesday` (string, required) - Days to filter places by
+ URL Params: 
    + Required: `days=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Body
    ```json
    [
        {
            "_id": "660880ef8747cd9210f22d03",
            "name": "CHURCH OF ST. NICHOLAS OF TOLENTINE",
            "address": "2345 University Ave, Bronx, NY, 10468",
            "contact": "(718) 295-6800",
            "tags": [],
            "hours": {
                "food_pantry": {
                    "Tuesday": [
                        {
                            "_id": "6680514f4899dda2c55dd6c6",
                            "open": "09:00",
                            "close": "11:00"
                        }
                    ]
                },
                "_id": "6680514f4899dda2c55dd6c7"
            },
            "borough": "Bronx",
            "notes": []
        },
        {
            "_id": "660881008747cd9210f22d06",
            "name": "GOD BLESS YOU ALL INC (QUEENS)",
            "address": "95-31 Jamaica Ave, Woodhaven, NY, 11421",
            "contact": "(347) 349-2720",
            "tags": [],
            "hours": {
                "food_pantry": {
                    "Monday": [
                        {
                            "_id": "6680514f4899dda2c55dd6c8",
                            "open": "11:00",
                            "close": "15:00"
                        }
                    ],
                    "Wednesday": [
                        {
                            "_id": "6680514f4899dda2c55dd6c9",
                            "open": "11:00",
                            "close": "15:00"
                        }
                    ]
                },
                "_id": "6680514f4899dda2c55dd6ca"
            },
            "borough": "Queens",
            "notes": []
        }
    ]
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "No places found within these operating times" }
    ```
    
### Search [/search]

**Retrieves places based on a fuzzy search term**

#### Parameters
| Parameter | Type   | Description                                      |
| --------- | ------ | ------------------------------------------------ |
| `name`    | string | Fuzzy search term to search for places by name   |

#### Examples

| Example                   | Validity       | Description                                      |
| ------------------------- | -------------- | ------------------------------------------------ |
| `/search?name=St.`        | Valid          | Retrieves places with names containing 'St.'      |
| `/search?name=Mar`        | Valid          | Retrieves places with names containing 'Mar'      |


#### Fetch Resource [GET]

+ Parameters
    + name: `St.` (string, required) - Fuzzy search term to filter places by
+ URL Params: 
    + Required: `name=[string]`
+ Data Params: None

+ Response 200 (application/json)
    + Body
    ```json
    [
            {
            "_id": "6608813a8747cd9210f22d10",
            "name": "ST. PETER'S CHURCH BREAKFAST PROGRAM",
            "address": "619 Lexington Ave, New York, NY, 10022",
            "contact": "(212) 935-2200",
            "tags": [],
            "hours": {
                "soup_kitchen": {
                    "Tuesday": [
                        {
                            "_id": "668054954899dda2c55de5c8",
                            "open": "07:15",
                            "close": "08:00"
                        }
                    ]
                },
                "_id": "668054954899dda2c55de5c9"
            },
            "borough": "Manhattan",
            "notes": []
        },
        {
            "_id": "6608813e8747cd9210f22d11",
            "name": "CHRIST CHURCH UNITED METHODIST",
            "address": "524 Park Ave, New York, NY, 10065",
            "contact": "(212) 838-3036",
            "tags": [],
            "hours": {
                "soup_kitchen": {
                    "Sunday": [
                        {
                            "_id": "668054954899dda2c55de5ca",
                            "open": "16:30",
                            "close": "18:00"
                        }
                    ]
                },
                "_id": "668054954899dda2c55de5cb"
            },
            "borough": "Manhattan",
            "notes": []
        },
    ]
    ```

+ Response 404 (application/json)
    + Body
    ```json
    { "error": "No places found within these operating times" }
    ```

## Data Models

### Place
+ Attributes
    + _id: `660a91248747cd35103e54ba` (string, required)
    + name: `Al Hajjah Fajr Tyson Halal Food and Clothing Distribution Pantry` (string, required)
    + address: `2269 Crotona Ave, Bronx, NY, 10457` (string, required)
    + contact: `(646) 353-0859` (string, required)
    + tags: `["Halal"]` (array[string], optional)
    + hours: `object` (object, required)
        + food_pantry: `object` (object, required)
            + Monday: `[{ "_id": "664d493a8d28da79ee488277", "open": "13:00", "close": "17:00" }]` (array[object], required)
            + Tuesday: `[{ "_id": "664d493a8d28da79ee488278", "open": "13:00", "close": "17:00" }]` (array[object], required)
            + Wednesday: `[{ "_id": "664d493a8d28da79ee488279", "open": "13:00", "close": "17:00" }]` (array[object], required)
            + Thursday: `[{ "_id": "664d493a8d28da79ee48827a", "open": "13:00", "close": "17:00" }]` (array[object], required)
            + Friday: `[{ "_id": "664d493a8d28da79ee48827b", "open": "13:00", "close": "17:00" }]` (array[object], required)
            + Saturday: `[{ "_id": "664d493a8d28da79ee48827c", "open": "13:00", "close": "17:00" }]` (array[object], required)
            + Sunday: `[{ "_id": "664d493a8d28da79ee48827d", "open": "13:00", "close": "17:00" }]` (array[object], required)
    + borough: `Bronx` (string, required)
    + notes: `[]` (array[object], optional)

### Note
+ Attributes
    + _id: `664d47d88d28da79ee488198` (string, required)
    + for: `All` (string, required)
    + note: `Once a month, please call for date` (string, required)